### ISSUE TITLE
org.mozilla.focus.fragment.BrowserFragment.goBack

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/FirefoxLite#2895]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.webkit.WebHistoryItem.getUrl()' on a null object reference
       at org.mozilla.focus.fragment.BrowserFragment.goBack(BrowserFragment.java:888)
       at org.mozilla.focus.fragment.BrowserFragment.onBackPressed(BrowserFragment.java:766)
       at org.mozilla.focus.activity.MainActivity.onBackPressed(MainActivity.java:928)
       at android.app.Activity.onKeyUp(Activity.java:3082)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2716)
       at android.app.Activity.dispatchKeyEvent(Activity.java:3365)
       at android.support.v4.app.SupportActivity.superDispatchKeyEvent(ComponentActivity.java:108)
       at android.support.v4.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
       at android.support.v4.app.SupportActivity.dispatchKeyEvent(ComponentActivity.java:126)
       at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
       at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
       at android.support.v7.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2533)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5038)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4906)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4586)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4643)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4454)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4427)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4480)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4446)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4619)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4780)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by chianger** [comment]
removing 'blocker' label for it's still a candidate. we'll determine after the STR is found

**Comment by chianger** [comment]
let's not block v1.0.1 shipping on this given we have no clear clue on the impact.

**Comment by chianger** [comment]
per current data showing it's top crash, let's fix this in v1.0.1.

**Comment by mTwTm** [comment]
I guess we should check: public boolean canGoBack() {
