### ISSUE TITLE
[Hot fix] update newspoint URL

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3345]

**Comment by Daisy-pliu** [comment]
Test case: ❌
[TC0202 ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B313)
Test verison : 1.2.1 (10853)

**Comment by Daisy-pliu** [comment]
Error Log:

2019-03-20 18:16:44.599 3605-3605/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.rocket.debug.firebase, PID: 3605
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter subcategory
        at org.mozilla.lite.newspoint.NewsPointItem.<init>(NewsPointItem.kt)
        at org.mozilla.lite.newspoint.RepositoryNewsPoint.lambda$static$0(RepositoryNewsPoint.java:55)
        at org.mozilla.lite.newspoint.-$$Lambda$RepositoryNewsPoint$ZvYynr31y46fQc7qiAJk6VMEhFM.parse(lambda)
        at org.mozilla.lite.partner.Repository$1.onChanged(Repository.java:126)
        at org.mozilla.lite.partner.Repository$1.onChanged(Repository.java:91)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at org.mozilla.cachedrequestloader.ResponseData.setValue(ResponseData.java:26)
        at org.mozilla.cachedrequestloader.ResponseData.setValue(ResponseData.java:8)
        at android.arch.lifecycle.LiveData$1.run(LiveData.java:87)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Daisy-pliu** [comment]
Verify : ✅
Test version: 1.2.1 (10858)
Test case: [refer ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B309)
