### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider org.mozilla.focus.provider.FirebaseHelperProvider: java.lang.IllegalStateException: Firebase related keys are not set

### ISSUE THREAD

**Issue by gh-debug** [mozilla-tw/FirefoxLite#4683]
1580672869.114 9176-9176/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mozilla.rocket, PID: 9176
    java.lang.RuntimeException: Unable to get provider org.mozilla.focus.provider.FirebaseHelperProvider: java.lang.IllegalStateException: Firebase related keys are not set
        at android.app.ActivityThread.installProvider(ActivityThread.java:6306)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5821)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5739)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)

**Comment by benjamin-cheng** [comment]
It seems you try to build Firebase flavor without the keys required by Firebase.
Please refer to the instructions If you would like to build `focusWebkitFirebase` flavor
https://github.com/mozilla-tw/Rocket/blob/4fedf245c4382122283ca8ec701a5ff18c9bf779/app/build.gradle#L346

Kind reminding, you could also build and develop Firefox Lite with `focusWebkitDebug` flavor, that's intent for no Firebase integration and does not require to setup the keys.

**Comment by Conjuror** [comment]
Close the issue since there's no more update for 19 days.
